## Component-wise Summary Report

```{r global_options, include=FALSE}
# setting global options 
figure.outpath <- paste(output.path,"/",prefix,"_figures/",sep="")
opts_chunk$set(fig.path=figure.outpath,dev=file.ext, warning=FALSE, message=FALSE)
```

### ICA Covariate Correlation Summary

```{r Covariate_correlation_summary,echo= FALSE,warning=FALSE,comment=NA,message=FALSE, fig.show = "hold", fig.width = 14,fig.height = 6 }
update_geom_defaults("bar",list(fill = "black"))

if(!is.null(ica.result$ica.stat.df)){
  
    summary.plots <- list()
    summary.plots[[1]] <- ggplot(ica.result$cov.corr.idx,aes(x = Covariate.Name,col = Covariate.Name)) + geom_bar()
    summary.plots[[2]] <- ggplot(ica.result$ica.stat.df,aes(x = N.peaks,group = corr.ic)) + 
                                  geom_bar(aes(fill = corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + xlab("Number of Peaks")
  
    summary.plots[[3]] <- ggplot(ica.result$ica.stat.df,aes(x = n.clust,group = corr.ic)) + 
                                  geom_bar(aes(fill= corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + xlab("Predicted of Clusters")
  
    summary.plots[[4]] <- ggplot(ica.result$ica.stat.df,aes(x = percent.var,group = corr.ic)) + 
                                  geom_bar(aes(fill= corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + xlab("Variance")
  
  
    for( p in 1:length(summary.plots)){
        summary.plots[[p]] <- summary.plots[[p]] +theme(axis.text = element_text(size=10), 
                                                        axis.title=element_text(size=12,face="bold"), 
                                                        title = element_text(size=14,face="bold"),
                                                        legend.position = "none",
                                                        panel.grid.major = element_line(colour = "grey80", linetype="dashed"),
                                                        panel.background = element_rect(fill = NA,color = "grey80")) 
    
        
    }
    
  multiplot(plotlist = summary.plots,cols = 2)
  
}
```

### Individual IC plots 

```{r Individual_IC_Plots, echo = FALSE,comment=NA,warning=FALSE, message=FALSE,fig.width = 10,fig.height = 5}

for( p in 1:dim(ica.result$A)[1]){
   
    # check if there is a specified order for the ICs (default is by explained variance)
    if(!is.null(ica.result$order)){
        i <- ica.result$order[p]
    } else {
        i <- p
    }
    
    # Running Mclust on IC coefficient to estimate ideal number of clusters in 1D IC coefficient space 
    mclust.obj <- suppressMessages(mclust::Mclust(ica.result$A[i,], modelNames = "V"))
    mclust.bic.df <- data.frame("V" = mclust.obj$BIC, "N.clust" = attr(mclust.obj$BIC,"G"))
    mclust.cer.df <- data.frame("uncertainty" = mclust.obj$uncertainty,"data" = mclust.obj$data )
  
    mclust.plots <- list()
   
   # Plot IC loading with peaks labeled in red (If peaks are available)
    if(!is.null(ica.result$peak.results)){
        # If the peaks are labeled use them 
        mclust.plots[[1]] <- plot_component(ica.result$S[,i],peaks = TRUE, 
                                            peakresult = ica.result$peak.results[[i]], 
                                            gene.names = rownames(ica.result$S),
                                            plot.title = paste(data.set,"_IC#_",i,sep =""))    
    } else {
        # If no peak labeling is available color them in black
        mclust.plots[[1]] <- plot_component(ica.result$S[,i],
                                            plot.title = paste(data.set,"_IC#_",i,sep =""))    
   
    }
    
    # Gene weight histogram plot (Investigating the non-normality of the component )
    mclust.plots[[4]] <- plot_component_hist(ica.result$S[,i],"Gene Weight Histogram")
   
    # create a data frame for plotting
    if(!is.null(colnames(ica.result$A)) & !is.null(info.df)){
      
        # Dataframe that will go into ggplot for plotting with IC coefficients in IC and idx as sample index
        coeff.plot.df <- data.frame(as.data.frame(info.df[colnames(ica.result$A),]),
                                    "IC" = ica.result$A[i,],
                                    "idx"=c(1:dim(ica.result$A)[2]))
        
        # Setting the colnames to covariate names
        colnames(coeff.plot.df)[1:dim(as.data.frame(info.df[colnames(ica.result$A),]))[2]] <- colnames(info.df) 
        } else if (is.null(info.df)) {
          
        # If there is no sample information available
        coeff.plot.df <- data.frame("IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
    
        } else {
          
        coeff.plot.df <- data.frame(as.data.frame(info.df),"IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
    
    }
    
   # If IC is correlated to a covariate color the pot accordingly
    if(i %in% unique(ica.result$cov.corr.idx$Signal.idx)){
      
        # color the graph by the covariate with the most significant association
        color.by <- names(which.min(ica.result$cov.pval.mx[i, as.character(ica.result$cov.corr.idx$Covariate.Name[which(ica.result$cov.corr.idx$Signal.idx == i)])]))
       mclust.plots[[2]] <- plot_coeff_w_legend(coeff.plot.df, k.col = color.by,
                                                plot.title = paste("Covariate = ",color.by,sep=""))
                            + theme(legend.position ="none")
       
       # Extra if statement for covariates that are not a factor (cannot produce a boxplot with individual groups)
       # Need to figure out which plot might be most effective
       
           if(class(info.df[,color.by]) == "factor"){
                  mclust.plots[[3]] <- ggplot(coeff.plot.df, aes_string(x = color.by, y = "IC", color = color.by)) + 
                                              geom_boxplot() + xlab("Covariate") + ylab("") +  
                                              theme(axis.ticks = element_blank(), axis.text.x = element_blank()) 
            
           } else{
              mclust.plots[[3]] <- ggplot(coeff.plot.df, aes_string(x = color.by, y = "IC", color = color.by)) + 
                                          geom_point() + xlab("Covariate")  + ylab("") +
                                          theme(axis.ticks = element_blank(), axis.text.x = element_blank())
           }

      } else if(mclust.obj$G != 1){
      
        # If IC is not correlated to covariate color it using the clustering information obtained from mclust
    
        coeff.plot.df$mclust <- factor(mclust.obj$classification)
        
        mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                    geom_point(size = 3, pch = 20) + 
                                    xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                    scale_color_brewer(palette = "Set1") 
        
        mclust.plots[[3]] <- ggplot(coeff.plot.df, aes(x = mclust, y = IC, color = mclust)) + 
                                    geom_boxplot() + xlab("Covariate") + ylab("") +  
                                    theme(axis.ticks = element_blank(), axis.text.x = element_blank())
  
    } else {
        coeff.plot.df$mclust <- factor(rep(1,dim(coeff.plot.df)[1]))
        
        mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                    geom_point(size = 3, pch = 20) + 
                                    xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                    scale_color_brewer(palette = "Set1") + theme(legend.position = "none")
        
        mclust.plots[[3]] <-  ggplot(coeff.plot.df, aes(x = IC)) + xlab("IC Coefficients") + ylab("")+
                                      geom_histogram(aes(y = ..density..)) + geom_density()
    }
  
   
  
    layout <- matrix(c(1,1,4,4,
                       2,2,3,3), byrow = T,ncol = 4)
  
    
    for( k in 1:length(mclust.plots)){
        mclust.plots[[k]] <- mclust.plots[[k]] +theme(axis.text = element_text(size=12), 
            axis.title=element_text(size=14,face="bold"), 
            title = element_text(size=16,face="bold"),
            legend.title = element_text(size=10, face="bold"),
            legend.text = element_text(size = 8),
            legend.key = element_rect(fill = NA,color = "white"),
            panel.grid.major = element_line(colour = "grey80", linetype="dashed"),
            panel.background = element_rect(fill = NA,color = "grey80")) 
      
    }
    
    cat("--------------------------------------------------------------------------------------------------------------","\n")
    if (i %in% unique(ica.result$cov.corr.idx$Signal.idx)){
        cat("IC # ",i," Correlation with covariate ", color.by,
            "/ P-value = ",ica.result$cov.pval.mx[i,color.by],"/ Variance (%) = ",ica.result$percent.var[i],"\n")    
        
    } else {
        cat("IC # ",i," No correlation with covariates / Variance (%) = ",ica.result$percent.var[i],"\n")
        
    }
    cat("--------------------------------------------------------------------------------------------------------------","\n")
  
    suppressMessages(multiplot(plotlist = mclust.plots, layout = layout))
    
}

```

