## Independent Component Analysis Summary Report

```{r global_options, include=FALSE}
# setting global options 
figure.outpath <- paste(output.path,"/icreport_figures/",prefix,"/",sep="")
opts_chunk$set(fig.path=figure.outpath,dev=file.ext, warning=FALSE, message=FALSE)
options(warn=-1)
```

### Covariate Correlation Summary

```{r Covariate_correlation_summary,echo= FALSE,warning=FALSE,comment=NA,message=FALSE, fig.show = "hold", fig.width = 14,fig.height = 6 }
update_geom_defaults("bar",list(fill = "black"))

if(!is.null(ica.result$hclust)){
      n.ics <- dim(ica.result$A)[1]
      plot(ica.result$hclust$plot, labels = FALSE, main = paste("Hierarchical Clustering of Multiple ICA Runs /",
                                                                n.ics,"significant ICs"))
      abline(h=ica.result$hclust$cutoff, col="red", lty=2)
  
}


if(!is.null(ica.result$info.df)){
  

    covariates <- unique(ica.result$cov.corr.idx$Covariate.Name)
    
    covariate.gene.df <- data.frame(matrix(nrow = length(covariates), ncol = 3))
    colnames(covariate.gene.df) <- c("Covariate","NumberOfGenes","NumberOfICs")
    
    for( c in 1: length(covariates)){
        single.covariate <- subset(ica.result$cov.corr.idx, Covariate.Name == covariates[c])
        ic.index <- single.covariate$IC
        if(length(ic.index) > 1){
            peaks.for.covariate <- sapply(1:length(ic.index), function(x) ica.result$peaks[[ic.index[x]]])
            peaks.for.covariate <- unlist(peaks.for.covariate)
            covariate.peaks <- unique(names(peaks.for.covariate))      
        } else {
            covariate.peaks <- ica.result$peaks[[ic.index]]
            
        }
        covariate.gene.df[c,1] <- covariates[c]
        covariate.gene.df[c,2] <- length(covariate.peaks)
        covariate.gene.df[c,3] <- length(ic.index)
    }
    
    covaraite.gene.df <- covariate.gene.df[order(covariate.gene.df$NumberOfICs, decreasing = TRUE),]
    covariate.gene.df$Covariate <- factor(covariate.gene.df$Covariate, 
                                          levels = c(covariate.gene.df$Covariate))
    #ica.result$cov.corr.idx <- within(ica.result$cov.corr.idx, 
    #                                  Covariate.Name <- factor(Covariate.Name, 
    #                                  levels=names(sort(table(Covariate.Name), 
    #                                                    decreasing=TRUE))))
    
    summary.plots <- list()
    
    if(length(covariates) < 8){
        flower.palette <- c("#283545","#E09E12","#A72613","#95CDDC","#395717","#3A3B35","#D68931","#442243")
        summary.plots[[1]] <- ggplot(covariate.gene.df,aes(x = Covariate, fill = Covariate, y = NumberOfICs)) + 
                                geom_bar(stat = 'identity',col = "black", width = .5) + scale_fill_manual(values=flower.palette) + ylab("Number of ICs")
        summary.plots[[2]] <- ggplot(covariate.gene.df,aes(x = Covariate, y = NumberOfGenes,fill = Covariate)) + 
                                geom_bar(stat = 'identity',col = "black", width = .5) + 
                                scale_fill_manual(values=flower.palette) + ylab("Number of Genes")
    } else {
        summary.plots[[1]] <- ggplot(covariate.gene.df,aes(x = Covariate, y = NumberOfICs, fill = Covariate)) + 
                                geom_bar(stat = 'identity',col = "black", width = .5) + ylab("Number of ICs")
        summary.plots[[2]] <- ggplot(covariate.gene.df,aes(x = Covariate, y = NumberOfGenes,fill = Covariate)) + 
                        geom_bar(stat = 'identity',col = "black", width = .5) + ylab("Number of Genes")

    }
    
    summary.plots[[3]] <- ggplot(ica.result$ica.stat.df,aes(x = N.peaks,group = corr.ic)) + 
                                  geom_bar(aes(fill = corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + 
                                  xlab("Number of Peaks") + ylab("Number of ICs")
  
    summary.plots[[4]] <- ggplot(ica.result$ica.stat.df,aes(x = n.clust,group = corr.ic)) + 
                                  geom_bar(aes(fill= corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + 
                                  xlab("Predicted of Clusters") + ylab("Number of ICs")
  
    summary.plots[[5]] <- ggplot(ica.result$ica.stat.df,aes(x = percent.var,group = corr.ic)) + 
                                  geom_bar(aes(fill= corr.ic)) + scale_fill_manual(values=c("grey50","darkred")) + 
                                  xlab("Variance(%) Explained") + ylab("Number of ICs")
  
  
    for( p in 1:length(summary.plots)){
        summary.plots[[p]] <- summary.plots[[p]] +theme(axis.text = element_text(size=10), 
                                                        axis.title=element_text(size=12,face="bold"), 
                                                        title = element_text(size=14,face="bold"),
                                                        legend.position = "none",
                                                        panel.grid.major = element_line(colour = "grey80", linetype="dashed"),
                                                        panel.background = element_rect(fill = NA,color = "grey80")) 
    
        
    }
    
}
```

```{r summary_1row,echo= FALSE,warning=FALSE,comment=NA,message=FALSE, fig.show = "hold", fig.width = 12,fig.height = 4 }

if(!is.null(ica.result$info.df)){
    if(length(covariates) < 7){
      multiplot(plotlist = list(summary.plots[[1]],summary.plots[[2]]), cols = 2)
}  
}
```

```{r summary_2row,echo= FALSE,warning=FALSE,comment=NA,message=FALSE, fig.show = "hold", fig.width = 12,fig.height = 6 }

if(!is.null(ica.result$info.df)){
    if(length(covariates) > 6){
          multiplot(plotlist = list(summary.plots[[1]],summary.plots[[2]]), cols = 1)
    }
}
```

```{r summary_plot2,echo= FALSE,warning=FALSE,comment=NA,message=FALSE, fig.show = "hold", fig.width = 12,fig.height = 4 }
if(!is.null(ica.result$info.df)){
    multiplot(plotlist = list(summary.plots[[3]],summary.plots[[4]], summary.plots[[5]]),cols = 3)
}
```

### Individual IC plots 

```{r Individual_IC_Plots, echo = FALSE,comment=NA,warning=FALSE, message=FALSE,fig.width = 10,fig.height = 5}

for( p in 1:dim(ica.result$A)[1]){
   
    if(is.null(ica.result$geneinfo)){
        ###################### Plotting without Gene information ########################## 
        # check if there is a specified order for the ICs (default is by explained variance)
        if(!is.null(ica.result$order)){
            i <- ica.result$order[p]
        } else {
            i <- p
        }
        
        # Running Mclust on IC coefficient to estimate ideal number of clusters in 1D IC coefficient space 
        mclust.obj <- suppressMessages(mclust::Mclust(ica.result$A[i,], modelNames = "V"))
      
        mclust.plots <- list()
       
       # Plot IC loading with peaks labeled in red (If peaks are available)
        if(!is.null(ica.result$peaks)){
            # If the peaks are labeled use them 
            mclust.plots[[1]] <- plot_component(ica.result$S[,i],peaks = TRUE, 
                                                peakresult = ica.result$peaks[[i]], 
                                                gene.names = rownames(ica.result$S),
                                                plot.title = paste(data.set,"_IC#_",i,sep =""))    
        } else {
            # If no peak labeling is available color them in black
            mclust.plots[[1]] <- plot_component(ica.result$S[,i],
                                                plot.title = paste(data.set,"_IC#_",i,sep =""))    
       
        }
        
        # Gene weight histogram plot (Investigating the non-normality of the component )
        mclust.plots[[4]] <- plot_component_hist(ica.result$S[,i],"Gene Weight Histogram")
       
        # create a data frame for plotting
        if(!is.null(colnames(ica.result$A)) & !is.null(info.df)){
          
            # Dataframe that will go into ggplot for plotting with IC coefficients in IC and idx as sample index
            coeff.plot.df <- data.frame(as.data.frame(info.df[colnames(ica.result$A),]),
                                        "IC" = ica.result$A[i,],
                                        "idx"=c(1:dim(ica.result$A)[2]))
            
            # Setting the colnames to covariate names
            colnames(coeff.plot.df)[1:dim(as.data.frame(info.df[colnames(ica.result$A),]))[2]] <- colnames(info.df) 
            } else if (is.null(info.df)) {
              
            # If there is no sample information available
            coeff.plot.df <- data.frame("IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
        
            } else {
              
            coeff.plot.df <- data.frame(as.data.frame(info.df),"IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
        
        }
        
       # If IC is correlated to a covariate color the pot accordingly
        if(i %in% unique(ica.result$cov.corr.idx$IC)){
          
        # color the graph by the covariate with the most significant association
        color.by <- names(which.min(ica.result$cov.pval.mx[i, as.character(ica.result$cov.corr.idx$Covariate.Name[which(ica.result$cov.corr.idx$IC == i)])]))
        mclust.plots[[2]] <- plot_coeff_w_legend(coeff.plot.df, k.col = color.by,
                                            plot.title = paste("Covariate = ",color.by,sep="")) + 
                                            theme(legend.position ="none")
        
        # Extra if statement for covariates that are not a factor (cannot produce a boxplot with individual groups)
        # Need to figure out which plot might be most effective
        
            if(class(info.df[,color.by]) == "factor"){
                  mclust.plots[[3]] <- ggplot(coeff.plot.df, aes_string(x = color.by, y = "IC", color = color.by)) + 
                                              geom_boxplot() + xlab("Covariate") + ylab("") +  
                                              theme(axis.ticks = element_blank(), axis.text.x = element_blank()) 
            
            } else{
                  mclust.plots[[3]] <- ggplot(coeff.plot.df, aes_string(x = color.by, y = "IC", color = color.by)) + 
                                          geom_point() + xlab("Covariate")  + ylab("") +
                                          theme(axis.ticks = element_blank(), axis.text.x = element_blank())
            }
            


          } else if(mclust.obj$G != 1){
          
            # If IC is not correlated to covariate color it using the clustering information obtained from mclust
        
            coeff.plot.df$mclust <- factor(mclust.obj$classification)
            
            mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                        geom_point(size = 3, pch = 20) + 
                                        xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                        scale_color_brewer(palette = "Set1") 
            
            mclust.plots[[3]] <- ggplot(coeff.plot.df, aes(x = mclust, y = IC, color = mclust)) + 
                                        geom_boxplot() + xlab("Covariate") + ylab("") +  
                                        theme(axis.ticks = element_blank(), axis.text.x = element_blank())
      
        } else {
            coeff.plot.df$mclust <- factor(rep(1,dim(coeff.plot.df)[1]))
            
            mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                        geom_point(size = 3, pch = 20) + 
                                        xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                        scale_color_brewer(palette = "Set1") + theme(legend.position = "none")
            
            mclust.plots[[3]] <-  ggplot(coeff.plot.df, aes(x = IC)) + xlab("IC Coefficients") + ylab("")+
                                          geom_histogram(aes(y = ..density..)) + geom_density()
        }
      
       
      
        layout <- matrix(c(1,1,4,4,
                           2,2,3,3), byrow = T,ncol = 4)
      
        
        for( k in 1:length(mclust.plots)){
            mclust.plots[[k]] <- mclust.plots[[k]] +theme(axis.text = element_text(size=12), 
                axis.title=element_text(size=14,face="bold"), 
                title = element_text(size=16,face="bold"),
                legend.title = element_text(size=10, face="bold"),
                legend.text = element_text(size = 8),
                legend.key = element_rect(fill = NA,color = "white"),
                panel.grid.major = element_line(colour = "grey80", linetype="dashed"),
                panel.background = element_rect(fill = NA,color = "grey80")) 
          
        }
        
        cat("--------------------------------------------------------------------------------------------------------------","\n")
        if (i %in% unique(ica.result$cov.corr.idx$IC)){
            cat("IC # ",i," Correlation with covariate ", color.by,
                "/ P-value = ",ica.result$cov.pval.mx[i,color.by],"/ Variance (%) = ",ica.result$percent.var[i],"\n")    
            
        } else {
            cat("IC # ",i," No correlation with covariates / Variance (%) = ",ica.result$percent.var[i],"\n")
            
        }
        cat("--------------------------------------------------------------------------------------------------------------","\n")
      
        suppressMessages(multiplot(plotlist = mclust.plots, layout = layout))
    } else if (!is.null(ica.result$geneinfo)) {
        ###################### Plotting with Gene information ##########################        
        if(!is.null(ica.result$order)){
            i <- ica.result$order[p]
        } else {
            i <- p
        }
        
        # Running Mclust on IC coefficient to estimate ideal number of clusters in 1D IC coefficient space 
        mclust.obj <- suppressMessages(mclust::Mclust(ica.result$A[i,], modelNames = "V"))
      
        mclust.plots <- list()
       
       # Plot IC loading with peaks labeled in red (If peaks are available)
        if(!is.null(ica.result$peaks)){
            # If the peaks are labeled use them 
            mclust.plots[[1]] <- plot_component(ica.result$S[,i],peaks = TRUE, 
                                                peakresult = ica.result$peaks[[i]], 
                                                gene.names = rownames(ica.result$S),
                                                plot.title = paste(data.set,"_IC#_",i,sep =""))    
        } else {
            # If no peak labeling is available color them in black
            mclust.plots[[1]] <- plot_component(ica.result$S[,i],
                                                plot.title = paste(data.set,"_IC#_",i,sep =""))    
       
        }
        
        # create a data frame for plotting
        if(!is.null(colnames(ica.result$A)) & !is.null(info.df)){
          
            # Dataframe that will go into ggplot for plotting with IC coefficients in IC and idx as sample index
            coeff.plot.df <- data.frame(as.data.frame(info.df[colnames(ica.result$A),]),
                                        "IC" = ica.result$A[i,],
                                        "idx"=c(1:dim(ica.result$A)[2]))
            
            # Setting the colnames to covariate names
            colnames(coeff.plot.df)[1:dim(as.data.frame(info.df[colnames(ica.result$A),]))[2]] <- colnames(info.df) 
            } else if (is.null(info.df)) {
              
            # If there is no sample information available
            coeff.plot.df <- data.frame("IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
        
            } else {
              
            coeff.plot.df <- data.frame(as.data.frame(info.df),"IC" = ica.result$A[i,],"idx"=c(1:dim(ica.result$A)[2]))
        
        }
        
       # If IC is correlated to a covariate color the pot accordingly
        if(i %in% unique(ica.result$cov.corr.idx$IC)){
          
            # color the graph by the covariate with the most significant association
            color.by <- names(which.min(ica.result$cov.pval.mx[i, as.character(ica.result$cov.corr.idx$Covariate.Name[which(ica.result$cov.corr.idx$IC == i)])]))
           mclust.plots[[2]] <- plot_coeff_w_legend(coeff.plot.df, k.col = color.by,
                                                    plot.title = paste("Covariate = ",color.by,sep=""))
           
           # Extra if statement for covariates that are not a factor (cannot produce a boxplot with individual groups)
           # Need to figure out which plot might be most effective
  
          } else if(mclust.obj$G != 1){
          
            # If IC is not correlated to covariate color it using the clustering information obtained from mclust
        
            coeff.plot.df$mclust <- factor(mclust.obj$classification)
            
            mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                        geom_point(size = 3, pch = 20) + 
                                        xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                        scale_color_brewer(palette = "Set1") 

      
        } else {
            coeff.plot.df$mclust <- factor(rep(1,dim(coeff.plot.df)[1]))
            
            mclust.plots[[2]] <- ggplot(coeff.plot.df, aes(x= idx, y = IC, color = mclust)) + 
                                        geom_point(size = 3, pch = 20) + 
                                        xlab("Sample idx") + ylab("IC coefficient") + labs(title = "Classification by Mclust") + 
                                        scale_color_brewer(palette = "Set1") + theme(legend.position = "none")
        }
      
         
        # Gene Information plots
        
        geneinfo.df <- ica.result$geneinfo[[i]]
        geneinfo.df$length <- geneinfo.df$end_position - geneinfo.df$start_position
        
        geneinfo.df <- na.omit(data.frame(geneinfo.df,"gene_weight" = abs(ica.result$peaks[[i]][as.character(geneinfo.df$row_ids)])))

        # chromosome summary plot
        mclust.plots[[3]] <- ggplot(geneinfo.df, aes(x = chromosome_name, fill = chromosome_name, y = gene_weight)) + geom_bar(stat = "identity") + 
                                     theme(legend.position = "none") + xlab("Chromosome") + scale_x_discrete(drop=FALSE) +
                                     scale_fill_discrete(drop=TRUE,limits = levels(geneinfo.df$chromosome_name))
       
        # Biotype summary plot
        mclust.plots[[4]] <- ggplot(geneinfo.df, aes(x = gene_biotype, fill = gene_biotype)) + geom_histogram() + coord_flip() +
                                     theme_bw() + #theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") + 
                                     xlab("")  + theme(legend.position = "none") + 
                                     scale_x_discrete(drop=TRUE) +
                                     scale_fill_discrete(drop=TRUE, limits = levels(geneinfo.df$gene_biotype))
       
        # Length summary
        #mclust.plots[[5]] <- ggplot(geneinfo.df, aes(x = length, fill = gene_biotype)) + geom_histogram() + theme_bw() +
        #                             labs(title = "Gene Length by Biotype")
        
        
        layout <- matrix(c(1,1,2,2,
                           3,3,4,4), byrow = T,ncol = 4)
        

        for( k in 1:length(mclust.plots)){
            mclust.plots[[k]] <- mclust.plots[[k]] +theme(axis.text = element_text(size=10), 
                axis.title=element_text(size=12,face="bold"), 
                title = element_text(size=14,face="bold"),
                legend.title = element_text(size=8, face="bold"),
                legend.text = element_text(size = 6),
                legend.key = element_rect(fill = NA,color = "white"),
                panel.grid.major = element_line(colour = "grey80", linetype="dashed"),
                panel.background = element_rect(fill = NA,color = "grey80")) 
          
        }
        mclust.plots[[4]] <- mclust.plots[[4]] + theme(axis.text = element_text(size = 6))
        cat("--------------------------------------------------------------------------------------------------------------","\n")
        if (i %in% unique(ica.result$cov.corr.idx$IC)){
            cat("IC # ",i," Correlation with covariate ", color.by,
                "/ P-value = ",ica.result$cov.pval.mx[i,color.by],"/ Variance (%) = ",ica.result$percent.var[i],"\n")    
            
        } else {
            cat("IC # ",i," No correlation with covariates / Variance (%) = ",ica.result$percent.var[i],"\n")
            
        }
        cat("--------------------------------------------------------------------------------------------------------------","\n")
      
        suppressMessages(multiplot(plotlist = mclust.plots, layout = layout))
      
      
      
      
    }

    
}

```

